SELECT TOP (1000) [full_name]
      ,[Place]
      ,[Time]
      ,[Total_Minutes]
      ,[City]
      ,[State]
      ,[Age]
      ,[Gender]
      ,[latlong]
  FROM [Marathon].[dbo].[vw_ff_50]
